c=======================================================================
c** Effective adiabatic radial potential variables.
      INTEGER BOBCN(NSTATEMX),PSEL(NSTATEMX),MAXMIN(NSTATEMX),
     1 IOMEG(NSTATEMX),Nbeta(NSTATEMX),APSE(NSTATEMX),IFXDE(NSTATEMX),
     2 IFXRE(NSTATEMX),IFXrefq(NSTATEMX),IFXrefp(NSTATEMX),
     3 IFXCm(NCMMax,NSTATEMX),IFXBETA(0:NbetaMX,NSTATEMX),
     4 NDATPT(NSTATEMX),NCMM(NSTATEMX),MMLR(NCMMax,NSTATEMX),
     5 pPOT(NSTATEMX),qPOT(NSTATEMX),pAD(NSTATEMX),qAD(NSTATEMX),
     6 LRad(NSTATEMX),pNA(NSTATEMX),qNA(NSTATEMX),Pqw(NSTATEMX),
     7 IVSR(NSTATEMX),IDSTT(NSTATEMX)
c
      REAL*8 DE(NSTATEMX),RE(NSTATEMX),BETA(0:NbetaMX,NSTATEMX),
     1 yqBETA(NbetaMX,NSTATEMX),BETAFX(NPNTMX,NSTATEMX),RH(NSTATEMX),
     2 RMIN(NSTATEMX),RMAX(NSTATEMX),VLIM(NSTATEMX),EPS(NSTATEMX),
     3 betaINF(NSTATEMX),AGPEF(NSTATEMX),BGPEF(NSTATEMX),
     4 CmVAL(NCMMax,NSTATEMX),CmEFF(NCMMax,NSTATEMX),rhoAB(NSTATEMX),
     5 AA(NSTATEMX),BB(NSTATEMX),RREFq(NSTATEMX),RREFp(NSTATEMX),
     6 ASO(NSTATEMX),R01(NSTATEMX),Q12(NSTATEMX),RD(NPNTMX,NSTATEMX),
     7 VPOT(NPNTMX,NSTATEMX),dCmA(NCMMax,NSTATEMX),dCmB(NCMMax,NSTATEMX)
c
      COMMON /BLKPOT/DE,RE,BETA,yqBETA,BETAFX,RH,RMIN,RMAX,VLIM,EPS,
     1 betaINF,AGPEF,BGPEF,CmVAL,CmEFF,rhoAB,AA,BB,RREFq,RREFp,ASO,R01,
     2 Q12,RD,VPOT,dCmA,dCmB, BOBCN,PSEL,MAXMIN,IOMEG,Nbeta,APSE,IFXDE,
     3 IFXRE,IFXrefq,IFXrefp,IFXCm,IFXBETA,NDATPT,NCMM,MMLR,pPOT,qPOT,
     4 pAD,qAD,LRad,pNA,qNA,Pqw,IVSR,IDSTT
c=======================================================================
