c=======================================================================
c** Effective adiabatic radial potential variables.
      INTEGER BOBCN(NSTATEMX),PSEL(NSTATEMX),MAXMIN(NSTATEMX),
     1 IOMEG(NSTATEMX),NSR(NSTATEMX),Nbeta(NSTATEMX),IFXDE(NSTATEMX),
     2 IFXRE(NSTATEMX),IFXCm(NCMMax,NSTATEMX),
     3 IFXBETA(0:NbetaMX,NSTATEMX),NDATPT(NSTATEMX),NCMM(NSTATEMX),
     4 MMLR(NCMMax,NSTATEMX),Pqw(NSTATEMX),IVSR(NSTATEMX),
     5 IDSTT(NSTATEMX)
c
      REAL*8 DE(NSTATEMX),RE(NSTATEMX),BETA(0:NbetaMX,NSTATEMX),
     1 ypBETA(NbetaMX,NSTATEMX),BETAFX(NPNTMX,NSTATEMX),RH(NSTATEMX),
     2 RMIN(NSTATEMX),RMAX(NSTATEMX),VLIM(NSTATEMX),EPS(NSTATEMX),
     3 betaINF(NSTATEMX),AGPEF(NSTATEMX),BGPEF(NSTATEMX),
     4 CmVAL(NCMMax,NSTATEMX),rhoAB(NSTATEMX),AA(NSTATEMX),
     5 BB(NSTATEMX),RREF(NSTATEMX),ASO(NSTATEMX),R01(NSTATEMX),
     6 Q12(NSTATEMX),RD(NPNTMX,NSTATEMX),VPOT(NPNTMX,NSTATEMX),
     7 nPB(NSTATEMX),nQB(NSTATEMX),pAD(NSTATEMX),qAD(NSTATEMX),
     8 pNA(NSTATEMX),qNA(NSTATEMX)
c
      COMMON /BLKPOT/DE,RE,BETA,ypBETA,BETAFX,RH,RMIN,RMAX,VLIM,EPS,
     1 betaINF,AGPEF,BGPEF,CmVAL,rhoAB,AA,BB,RREF,ASO,R01,Q12,RD,VPOT,
     2 nPB,nQB,pAD,qAD,pNA,qNA,BOBCN,PSEL,MAXMIN,IOMEG,NSR,Nbeta,
     3 IFXDE,IFXRE,IFXCm,IFXBETA,NDATPT,NCMM,MMLR,Pqw,IVSR,IDSTT
c=======================================================================
