c=======================================================================
c** Effective adiabatic radial potential variables.
      INTEGER BOBCN(NSTATEMX),PSEL(NSTATEMX),MAXMIN(NSTATEMX),
     1 IOMEG(NSTATEMX),NSR(NSTATEMX),Nbeta(NSTATEMX),IFXDE(NSTATEMX),
     2 IFXRE(NSTATEMX),IFXCm(NCMMax,NSTATEMX),
     3 IFXBETA(0:NbetaMX,NSTATEMX),NDATPT(NSTATEMX),NCMM(NSTATEMX),
     4 MMLR(NCMMax,NSTATEMX),nPB(NSTATEMX),nQB(NSTATEMX),pAD(NSTATEMX),
     5 qAD(NSTATEMX),LRad(NSTATEMX),pNA(NSTATEMX),qNA(NSTATEMX),
     6 Pqw(NSTATEMX),IVSR(NSTATEMX),IDSTT(NSTATEMX)
c
      REAL*8 DE(NSTATEMX),RE(NSTATEMX),BETA(0:NbetaMX,NSTATEMX),
     1 ypBETA(NbetaMX,NSTATEMX),BETAFX(NPNTMX,NSTATEMX),RH(NSTATEMX),
     2 RMIN(NSTATEMX),RMAX(NSTATEMX),VLIM(NSTATEMX),EPS(NSTATEMX),
     3 betaINF(NSTATEMX),AGPEF(NSTATEMX),BGPEF(NSTATEMX),
     4 CmVAL(NCMMax,NSTATEMX),rhoAB(NSTATEMX),AA(NSTATEMX),
     5 BB(NSTATEMX),RREF(NSTATEMX),ASO(NSTATEMX),R01(NSTATEMX),
     6 Q12(NSTATEMX),RD(NPNTMX,NSTATEMX),VPOT(NPNTMX,NSTATEMX),
     7 dCmA(NCMMax,NSTATEMX),dCmB(NCMMax,NSTATEMX)

c
      COMMON /BLKPOT/DE,RE,BETA,ypBETA,BETAFX,RH,RMIN,RMAX,VLIM,EPS,
     1 betaINF,AGPEF,BGPEF,CmVAL,rhoAB,AA,BB,RREF,ASO,R01,Q12,RD,VPOT,
     2 dCmA,dCmB,BOBCN,PSEL,MAXMIN,IOMEG,NSR,Nbeta,IFXDE,IFXRE,IFXCm,
     3 IFXBETA,NDATPT,NCMM,MMLR,nPB,nQB,pAD,qAD,LRad,pNA,qNA,Pqw,IVSR,
     4 IDSTT
c=======================================================================
