c=======================================================================
c** Type statements & common blocks for characterizing transitions
      REAL*8  AVEUFREQ(NPARMX),MAXUFREQ(NPARMX)
      INTEGER NTRANSFS(NISTPMX,NSTATEMX),
     1  NTRANSVIS(NISTPMX,NSTATEMX,NSTATEMX),
     1  NBANDEL(NISTPMX,NSTATEMX,NSTATEMX),
     2  NTRANSIR(NISTPMX,NSTATEMX),NTRANSMW(NISTPMX,NSTATEMX),
     3  NBANDFS(NISTPMX,NSTATEMX),NBANDVIS(NISTPMX,NSTATEMX),
     4  NBANDIR(NISTPMX,NSTATEMX),NBANDMW(NISTPMX,NSTATEMX),
     5  NVVPP(NISTPMX,NSTATEMX),NWIDTH(NISTPMX,NSTATEMX),
     6  NEBPAS(NISTPMX,NSTATEMX),NVIRIAL(NISTPMX,NSTATEMX),
     7  NAcVIR(NISTPMX,NSTATEMX),NBANDS(NISTPMX)
c
      COMMON /BLKTYPE/AVEUFREQ,MAXUFREQ,NTRANSFS,NTRANSVIS,NTRANSIR,
     1  NTRANSMW,NBANDFS,NBANDEL,NBANDVIS,NBANDIR,NBANDMW,NVVPP,NWIDTH,
     2  NEBPAS,NVIRIAL,NAcVIR,NBANDS
c=======================================================================
